---


- name: Provision VM Linux
  hosts: "demo"
  become: true

  # vars:
  #  ansible_user:

  tasks:

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - awscli
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Add a new user for CI/CD
      user:
        name: github
        shell: /bin/bash
        groups: docker
        append: yes
        state: present
        # password: "{{ password }}"

    - name: Add authorized key to login
      authorized_key: user=github
        key="{{ lookup('file', 'files/github.pub') }}" state=present

  #  - name: Add user to docker group

