---

- name: Provision VM Windows
  hosts: "demo"

  vars:
    ansible_shell_type: powershell
    ansible_become_method: runas


  tasks:
    - name: test powershell
      win_shell: |
        get-host

    - name: Add secondary user
      win_user:
        name: SecondaryUser
        # password:
        state: present
        groups:
          - Remote Desktop Users

    - name: Install IIS and Dependency
      win_shell: |
        Install-WindowsFeature -name Web-Server -IncludeManagementTools; Enable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementScriptingTools; Enable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementService -All;

    - name: Install WebDeploy
      win_package:
        path: https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi
        # product_id: '{6773A61D-755B-4F74-95CC-97920E45E696}'
        arguments: ADDLOCAL=ALL
        state: present
