name: Ansible Windows CI

on:
  workflow_dispatch:

jobs:
  runPlaybookStep:
    name: RunPlaybook
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ github.workspace }}/ansible/windows-playbook.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [demo]
            ${{secrets.SSH_HOST}} ansible_user=Administrator
